services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soccer-note-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app-data:/var/www/html
    networks:
      - soccer-note-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: soccer-note-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - app-data:/var/www/html
    networks:
      - soccer-note-network
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: soccer-note-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - soccer-note-network

networks:
  soccer-note-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  app-data:
    driver: local
