/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * システム統計情報の取得
         * @description システム全体の統計情報を取得します
         */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザー登録
         * @description 新規ユーザーを登録します
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description ユーザーログインしてトークンを発行します
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト
         * @description 現在のトークンを無効化します
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 認証ユーザー情報取得
         * @description 現在認証されているユーザーの情報を取得します
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * プロフィール更新
         * @description 認証ユーザーのプロフィール情報を更新します
         */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * パスワード変更
         * @description 認証ユーザーのパスワードを変更します
         */
        put: operations["updatePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * グループ一覧取得
         * @description グループ一覧を取得します
         */
        get: operations["getGroups"];
        put?: never;
        /**
         * グループ作成
         * @description 新しいグループを作成します
         */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{sqid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * グループ詳細取得
         * @description 指定されたSqidのグループ詳細を取得します
         */
        get: operations["getGroup"];
        /**
         * グループ更新
         * @description 指定されたSqidのグループを更新します
         */
        put: operations["updateGroup"];
        post?: never;
        /**
         * グループ削除
         * @description 指定されたSqidのグループを削除します
         */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description APIサーバーの稼働状態を確認します
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ノート一覧取得
         * @description ログインユーザーのノート一覧を取得します
         */
        get: operations["getNotes"];
        put?: never;
        /**
         * ノート作成
         * @description 新しいノートを作成します
         */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{sqid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ノート詳細取得
         * @description 指定されたSqidのノート詳細を取得します
         */
        get: operations["getNote"];
        /**
         * ノート更新
         * @description 指定されたSqidのノートを更新します
         */
        put: operations["updateNote"];
        post?: never;
        /**
         * ノート削除
         * @description 指定されたSqidのノートを削除します
         */
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 権限一覧取得
         * @description すべての権限を取得します
         */
        get: operations["getPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * チーム一覧取得
         * @description チーム一覧を取得します
         */
        get: operations["getTeams"];
        put?: never;
        /**
         * チーム作成
         * @description 新しいチームを作成します
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{sqid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * チーム詳細取得
         * @description 指定されたSqidのチーム詳細を取得します
         */
        get: operations["getTeam"];
        /**
         * チーム更新
         * @description 指定されたSqidのチームを更新します
         */
        put: operations["updateTeam"];
        post?: never;
        /**
         * チーム削除
         * @description 指定されたSqidのチームを削除します
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{sqid}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * チームのユーザー一覧取得
         * @description 指定されたSqidのチームに所属するユーザー一覧を取得します
         */
        get: operations["getTeamUsers"];
        put?: never;
        /**
         * チームにユーザーを追加
         * @description 指定されたSqidのチームにユーザーを追加します
         */
        post: operations["addUserToTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{sqid}/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * チームのユーザー情報を更新
         * @description 指定されたSqidのチームに所属するユーザーの情報を更新します
         */
        put: operations["updateTeamUser"];
        post?: never;
        /**
         * チームからユーザーを削除
         * @description 指定されたSqidのチームからユーザーを削除します
         */
        delete: operations["removeUserFromTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: components["schemas"]["User"]["email"];
            /**
             * Format: password
             * @example password123
             */
            password: string;
            /** @example iPhone 15 */
            device_name?: string;
        };
        RegisterRequest: {
            name: components["schemas"]["User"]["name"];
            email: components["schemas"]["User"]["email"];
            /**
             * Format: password
             * @example password123
             */
            password: string;
            /**
             * Format: password
             * @example password123
             */
            password_confirmation: string;
        };
        UpdatePasswordRequest: {
            /**
             * Format: password
             * @example oldpassword
             */
            current_password: string;
            /**
             * Format: password
             * @example newpassword123
             */
            password: string;
            /**
             * Format: password
             * @example newpassword123
             */
            password_confirmation: string;
        };
        UpdateProfileRequest: {
            name?: components["schemas"]["User"]["name"];
            email?: components["schemas"]["User"]["email"];
        };
        CreateGroupRequest: {
            team_id: components["schemas"]["Group"]["team_id"];
            name: components["schemas"]["Group"]["name"];
            description?: components["schemas"]["Group"]["description"];
        };
        UpdateGroupRequest: {
            team_id?: components["schemas"]["Group"]["team_id"];
            name?: components["schemas"]["Group"]["name"];
            description?: components["schemas"]["Group"]["description"];
        };
        CreateNoteRequest: {
            title: components["schemas"]["Note"]["title"];
            date: components["schemas"]["Note"]["date"];
            content: components["schemas"]["Note"]["content"];
        };
        UpdateNoteRequest: {
            title: components["schemas"]["Note"]["title"];
            date: components["schemas"]["Note"]["date"];
            content: components["schemas"]["Note"]["content"];
        };
        AddUserToTeamRequest: {
            /**
             * Format: int64
             * @description ユーザーID
             */
            user_id: number;
            /**
             * @description オーナーフラグ
             * @default false
             */
            is_owner: boolean;
        };
        CreateTeamRequest: {
            name: components["schemas"]["Team"]["name"];
            description?: components["schemas"]["Team"]["description"];
        };
        UpdateTeamRequest: {
            name?: components["schemas"]["Team"]["name"];
            description?: components["schemas"]["Team"]["description"];
        };
        UpdateTeamUserRequest: {
            /** @description オーナーフラグ */
            is_owner: boolean;
        };
        Group: {
            /**
             * Format: int64
             * @description グループID
             */
            id?: number;
            /**
             * @description Sqid (公開用ID)
             * @example aBc12DeF
             */
            sqid?: string;
            /**
             * Format: int64
             * @description チームID
             */
            team_id?: number;
            /** @description グループ名 */
            name?: string;
            /** @description グループの説明 */
            description?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
            /**
             * Format: date-time
             * @description 論理削除日時
             */
            deleted_at?: string | null;
        };
        Note: {
            /**
             * Format: int64
             * @description ノートID
             */
            id?: number;
            /**
             * @description Sqid (公開用ID)
             * @example aBc12DeF
             */
            sqid?: string;
            /**
             * Format: int64
             * @description ユーザーID
             */
            user_id?: number;
            /** @description タイトル */
            title?: string;
            /**
             * Format: date
             * @description 日付
             */
            date?: string;
            /** @description 内容 */
            content?: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
            /**
             * Format: date-time
             * @description 論理削除日時
             */
            deleted_at?: string | null;
        };
        Permission: {
            /**
             * Format: int64
             * @description 権限ID
             */
            id?: number;
            /** @description 権限識別子 */
            name?: string;
            /** @description 表示名 */
            display_name?: string;
            /** @description 権限の説明 */
            description?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
            /**
             * Format: date-time
             * @description 論理削除日時
             */
            deleted_at?: string | null;
        };
        Team: {
            /**
             * Format: int64
             * @description チームID
             */
            id?: number;
            /**
             * @description Sqid (公開用ID)
             * @example aBc12DeF
             */
            sqid?: string;
            /** @description チーム名 */
            name?: string;
            /** @description チームの説明 */
            description?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
            /**
             * Format: date-time
             * @description 論理削除日時
             */
            deleted_at?: string | null;
        };
        User: {
            /**
             * Format: int64
             * @description ユーザーID
             */
            id?: number;
            /**
             * @description Sqid (公開用ID)
             * @example xYz34WvU
             */
            sqid?: string;
            /** @description ユーザー名 */
            name?: string;
            /**
             * Format: email
             * @description メールアドレス
             */
            email?: string;
            /**
             * Format: date-time
             * @description メールアドレス確認日時
             */
            email_verified_at?: string | null;
            /**
             * Format: password
             * @description パスワード
             */
            password?: string;
            /** @description リメンバートークン */
            remember_token?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
            /**
             * Format: date-time
             * @description 論理削除日時
             */
            deleted_at?: string | null;
        };
        AdminStatsResponse: {
            /** @description 総ユーザー数 */
            total_users?: number;
            /** @description アクティブユーザー数 */
            active_users?: number;
            /** @description 総チーム数 */
            total_teams?: number;
            /** @description 総グループ数 */
            total_groups?: number;
            /** @description 総投稿数 */
            total_posts?: number;
        };
        GetProfileResponse: {
            id?: components["schemas"]["User"]["id"];
            name?: components["schemas"]["User"]["name"];
            email?: components["schemas"]["User"]["email"];
            email_verified_at?: components["schemas"]["User"]["email_verified_at"];
            created_at?: components["schemas"]["User"]["created_at"];
            updated_at?: components["schemas"]["User"]["updated_at"];
        };
        LoginResponse: {
            /** @example 1|abcdefghijklmnopqrstuvwxyz */
            token?: string;
            user?: {
                id?: components["schemas"]["User"]["id"];
                name?: components["schemas"]["User"]["name"];
                email?: components["schemas"]["User"]["email"];
            };
        };
        LogoutResponse: {
            /** @example ログアウトしました */
            message?: string;
        };
        RegisterResponse: {
            user?: {
                id?: components["schemas"]["User"]["id"];
                name?: components["schemas"]["User"]["name"];
                email?: components["schemas"]["User"]["email"];
                created_at?: components["schemas"]["User"]["created_at"];
            };
            /** @example 1|abcdefghijklmnopqrstuvwxyz */
            token?: string;
        };
        UpdatePasswordResponse: {
            /** @example パスワードを更新しました */
            message?: string;
        };
        UpdateProfileResponse: {
            id?: components["schemas"]["User"]["id"];
            name?: components["schemas"]["User"]["name"];
            email?: components["schemas"]["User"]["email"];
            email_verified_at?: components["schemas"]["User"]["email_verified_at"];
            created_at?: components["schemas"]["User"]["created_at"];
            updated_at?: components["schemas"]["User"]["updated_at"];
        };
        CreateGroupResponse: {
            id?: components["schemas"]["Group"]["id"];
            sqid?: components["schemas"]["Group"]["sqid"];
            team_id?: components["schemas"]["Group"]["team_id"];
            name?: components["schemas"]["Group"]["name"];
            description?: components["schemas"]["Group"]["description"];
            created_at?: components["schemas"]["Group"]["created_at"];
            updated_at?: components["schemas"]["Group"]["updated_at"];
        };
        GetGroupResponse: {
            id?: components["schemas"]["Group"]["id"];
            sqid?: components["schemas"]["Group"]["sqid"];
            team_id?: components["schemas"]["Group"]["team_id"];
            name?: components["schemas"]["Group"]["name"];
            description?: components["schemas"]["Group"]["description"];
            created_at?: components["schemas"]["Group"]["created_at"];
            updated_at?: components["schemas"]["Group"]["updated_at"];
        };
        GetGroupsResponse: {
            data?: {
                id?: components["schemas"]["Group"]["id"];
                sqid?: components["schemas"]["Group"]["sqid"];
                team_id?: components["schemas"]["Group"]["team_id"];
                name?: components["schemas"]["Group"]["name"];
                description?: components["schemas"]["Group"]["description"];
                created_at?: components["schemas"]["Group"]["created_at"];
                updated_at?: components["schemas"]["Group"]["updated_at"];
            }[];
            /** @example 1 */
            current_page?: number;
            /** @example 5 */
            last_page?: number;
            /** @example 15 */
            per_page?: number;
            /** @example 72 */
            total?: number;
        };
        UpdateGroupResponse: {
            id?: components["schemas"]["Group"]["id"];
            sqid?: components["schemas"]["Group"]["sqid"];
            team_id?: components["schemas"]["Group"]["team_id"];
            name?: components["schemas"]["Group"]["name"];
            description?: components["schemas"]["Group"]["description"];
            created_at?: components["schemas"]["Group"]["created_at"];
            updated_at?: components["schemas"]["Group"]["updated_at"];
        };
        CreateNoteResponse: {
            id?: components["schemas"]["Note"]["id"];
            user_id?: components["schemas"]["Note"]["user_id"];
            title?: components["schemas"]["Note"]["title"];
            date?: components["schemas"]["Note"]["date"];
            content?: components["schemas"]["Note"]["content"];
            created_at?: components["schemas"]["Note"]["created_at"];
            updated_at?: components["schemas"]["Note"]["updated_at"];
        };
        GetNoteResponse: {
            id?: components["schemas"]["Note"]["id"];
            user_id?: components["schemas"]["Note"]["user_id"];
            title?: components["schemas"]["Note"]["title"];
            date?: components["schemas"]["Note"]["date"];
            content?: components["schemas"]["Note"]["content"];
            created_at?: components["schemas"]["Note"]["created_at"];
            updated_at?: components["schemas"]["Note"]["updated_at"];
        };
        GetNotesResponse: {
            data?: {
                id?: components["schemas"]["Note"]["id"];
                sqid?: components["schemas"]["Note"]["sqid"];
                user_id?: components["schemas"]["Note"]["user_id"];
                title?: components["schemas"]["Note"]["title"];
                date?: components["schemas"]["Note"]["date"];
                content?: components["schemas"]["Note"]["content"];
                created_at?: components["schemas"]["Note"]["created_at"];
                updated_at?: components["schemas"]["Note"]["updated_at"];
            }[];
            /** @example 1 */
            current_page?: number;
            /** @example 5 */
            last_page?: number;
            /** @example 15 */
            per_page?: number;
            /** @example 72 */
            total?: number;
        };
        UpdateNoteResponse: {
            id?: components["schemas"]["Note"]["id"];
            user_id?: components["schemas"]["Note"]["user_id"];
            title?: components["schemas"]["Note"]["title"];
            date?: components["schemas"]["Note"]["date"];
            content?: components["schemas"]["Note"]["content"];
            created_at?: components["schemas"]["Note"]["created_at"];
            updated_at?: components["schemas"]["Note"]["updated_at"];
        };
        AddUserToTeamResponse: {
            /**
             * Format: int64
             * @description チームID
             */
            team_id?: number;
            /**
             * Format: int64
             * @description ユーザーID
             */
            user_id?: number;
            /** @description オーナーフラグ */
            is_owner?: boolean;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
        };
        CreateTeamResponse: {
            id?: components["schemas"]["Team"]["id"];
            sqid?: components["schemas"]["Team"]["sqid"];
            name?: components["schemas"]["Team"]["name"];
            description?: components["schemas"]["Team"]["description"];
            created_at?: components["schemas"]["Team"]["created_at"];
            updated_at?: components["schemas"]["Team"]["updated_at"];
        };
        GetTeamResponse: {
            id?: components["schemas"]["Team"]["id"];
            sqid?: components["schemas"]["Team"]["sqid"];
            name?: components["schemas"]["Team"]["name"];
            description?: components["schemas"]["Team"]["description"];
            created_at?: components["schemas"]["Team"]["created_at"];
            updated_at?: components["schemas"]["Team"]["updated_at"];
        };
        TeamUserItem: {
            /**
             * Format: int64
             * @description ユーザーID
             */
            id?: number;
            /** @description ユーザーSqid */
            sqid?: string;
            /** @description ユーザー名 */
            name?: string;
            /**
             * Format: email
             * @description メールアドレス
             */
            email?: string;
            /** @description オーナーフラグ */
            is_owner?: boolean;
            /**
             * Format: date-time
             * @description 参加日時
             */
            created_at?: string;
        };
        GetTeamUsersResponse: {
            data?: components["schemas"]["TeamUserItem"][];
        };
        GetTeamsResponse: {
            data?: {
                id?: components["schemas"]["Team"]["id"];
                sqid?: components["schemas"]["Team"]["sqid"];
                name?: components["schemas"]["Team"]["name"];
                description?: components["schemas"]["Team"]["description"];
                created_at?: components["schemas"]["Team"]["created_at"];
                updated_at?: components["schemas"]["Team"]["updated_at"];
            }[];
            /** @example 1 */
            current_page?: number;
            /** @example 5 */
            last_page?: number;
            /** @example 15 */
            per_page?: number;
            /** @example 72 */
            total?: number;
        };
        UpdateTeamResponse: {
            id?: components["schemas"]["Team"]["id"];
            sqid?: components["schemas"]["Team"]["sqid"];
            name?: components["schemas"]["Team"]["name"];
            description?: components["schemas"]["Team"]["description"];
            created_at?: components["schemas"]["Team"]["created_at"];
            updated_at?: components["schemas"]["Team"]["updated_at"];
        };
        UpdateTeamUserResponse: {
            /**
             * Format: int64
             * @description チームID
             */
            team_id?: number;
            /**
             * Format: int64
             * @description ユーザーID
             */
            user_id?: number;
            /** @description オーナーフラグ */
            is_owner?: boolean;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
        };
    };
    responses: {
        /** @description 認証エラー */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example 認証に失敗しました */
                    message?: string;
                };
            };
        };
        /** @description リソースが見つかりません */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example リソースが見つかりません */
                    message?: string;
                };
            };
        };
        /** @description バリデーションエラー */
        422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example The given data was invalid. */
                    message?: string;
                    /**
                     * @example {
                     *       "email": [
                     *         "メールアドレスは必須です。"
                     *       ],
                     *       "password": [
                     *         "パスワードは必須です。"
                     *       ]
                     *     }
                     */
                    errors?: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: {
        /** @description ページ番号 */
        page: number;
        /** @description 1ページあたりの件数 */
        per_page: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 統計情報の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
            401: components["responses"]["401"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description バリデーションエラー */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログアウト成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProfileResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfileResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description バリデーションエラー */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePasswordResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description バリデーションエラー */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroups: {
        parameters: {
            query?: {
                /** @description ページ番号 */
                page?: components["parameters"]["page"];
                /** @description 1ページあたりの件数 */
                per_page?: components["parameters"]["per_page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGroupsResponse"];
                };
            };
            401: components["responses"]["401"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGroupResponse"];
                };
            };
            401: components["responses"]["401"];
            422: components["responses"]["422"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description グループSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGroupResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description グループSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateGroupResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description グループSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description ステータス
                         * @example ok
                         */
                        status: string;
                        /**
                         * @description タイムスタンプ
                         * @example 2025-01-10T12:00:00Z
                         */
                        timestamp: string;
                    };
                };
            };
        };
    };
    getNotes: {
        parameters: {
            query?: {
                /** @description ページ番号 */
                page?: components["parameters"]["page"];
                /** @description 1ページあたりの件数 */
                per_page?: components["parameters"]["per_page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetNotesResponse"];
                };
            };
            401: components["responses"]["401"];
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateNoteResponse"];
                };
            };
            401: components["responses"]["401"];
            422: components["responses"]["422"];
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ノートSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetNoteResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ノートSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateNoteResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    deleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ノートSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    getPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @description 権限ID
                         * @example 1
                         */
                        id?: number;
                        /**
                         * @description 権限識別子
                         * @example view_notes
                         */
                        name?: string;
                        /**
                         * @description 表示名
                         * @example ノート閲覧
                         */
                        display_name?: string;
                        /**
                         * @description 権限の説明
                         * @example ノートを閲覧できる
                         */
                        description?: string | null;
                        /**
                         * Format: date-time
                         * @description 作成日時
                         */
                        created_at?: string;
                        /**
                         * Format: date-time
                         * @description 更新日時
                         */
                        updated_at?: string;
                    }[];
                };
            };
            401: components["responses"]["401"];
        };
    };
    getTeams: {
        parameters: {
            query?: {
                /** @description ページ番号 */
                page?: components["parameters"]["page"];
                /** @description 1ページあたりの件数 */
                per_page?: components["parameters"]["per_page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTeamsResponse"];
                };
            };
            401: components["responses"]["401"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTeamResponse"];
                };
            };
            401: components["responses"]["401"];
            422: components["responses"]["422"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTeamResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateTeamResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    getTeamUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTeamUsersResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    addUserToTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddUserToTeamRequest"];
            };
        };
        responses: {
            /** @description 追加成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddUserToTeamResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    updateTeamUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
                /** @description ユーザーID */
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamUserRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateTeamUserResponse"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    removeUserFromTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description チームSqid */
                sqid: string;
                /** @description ユーザーID */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
}
